
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { StepContextProvider } from "@/context/StepContext";
import SideBar from "@/components/SideBar";
import LayoutWrapper from "@/components/LayoutWrapper";
import { Toaster } from "sonner";
import AuthCheck from "@/components/AuthCheck";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StepContextProvider>

          <AuthCheck />
          <Navbar />
          <LayoutWrapper>{children}</LayoutWrapper>
          <Toaster position="bottom-right" />
        </StepContextProvider>
      </body>
    </html>
  );
}
