import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { StepContextProvider } from "@/context/StepContext";
import LayoutWrapper from "@/components/LayoutWrapper";
import { Toaster } from "sonner";
import { AuthProvider } from "../../AuthProvider";// Your new AuthProvider

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Wrap everything with AuthProvider */}
        <AuthProvider>
          <StepContextProvider>
            <Navbar />
            <LayoutWrapper>
              {/* Children will be automatically protected by individual ProtectedRoute components */}
              {children}
            </LayoutWrapper>
            <Toaster position="bottom-right" />
          </StepContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}